In [3]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
len(tokenizer.word_index)

17

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [8]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]])

In [13]:
import tensorflow as tf
print(tf.__version__)

2.16.2


In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=17, output_dim=2))

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.compile('adam','accuracy')

In [16]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
[[[-0.04029509  0.01241947]
  [-0.00342781  0.0166278 ]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]]

 [[-0.00342781  0.0166278 ]
  [-0.00342781  0.0166278 ]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]]

 [[-0.02619305  0.0283036 ]
  [-0.02619305  0.0283036 ]
  [-0.03157289 -0.0157372 ]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]]

 [[-0.01498988 -0.02034146]
  [-0.0016828  -0.00317749]
  [-0.01498988 -0.02034146]
  [-0.00342781  0.0166278 ]
  [-0.01498988 -0.02034146]]

 [[ 0.04254222 -0.00138682]
  [-0.02326243 -0.03638438]
  [ 0.01935326  0.0482057 ]
  [-0.027777    0.0165975 ]
  [-0.0065348   0.02127662]]

 [[ 0.04281645  0.01896972]
  [ 0.04281645  0.01896972]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]
  [-0.0065348   0.02127662]]

 [[ 0.00831259 -0.01760624]
  [ 0.00831259 -0.01760624]
  [-0.0065348   0.02127662]
  [-0.0065348   0.0212766

In [17]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

ModuleNotFoundError: No module named 'keras.preprocessing.text'

In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
model = Sequential()
model.add(Embedding(10000, 2,50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 2)           20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 40s 50ms/step - loss: 0.5801 - acc: 0.6731 - val_loss: 0.4433 - val_acc: 0.7978
Epoch 2/5
782/782 [==============================] - 39s 50ms/step - loss: 0.3524 - acc: 0.8510 - val_loss: 0.4430 - val_acc: 0.8051
Epoch 3/5
782/782 [==============================] - 39s 50ms/step - loss: 0.2040 - acc: 0.9224 - val_loss: 0.5460 - val_acc: 0.7828
Epoch 4/5
782/782 [==============================] - 38s 49ms/step - loss: 0.0823 - acc: 0.9735 - val_loss: 0.6990 - val_acc: 0.7824
Epoch 5/5
782/782 [==============================] - 38s 49ms/step - loss: 0.0352 - acc: 0.9894 - val_loss: 0.8774 - val_acc: 0.7670
