In [12]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN

In [13]:
model = Sequential([
  tf.keras.layers.Input((4, 5)),
	SimpleRNN(3),
 	Dense(1, activation='sigmoid')
])

print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [4]:
print(model.get_weights()[0].shape)
print(model.get_weights()[0])

(5, 3)
[[-0.7399174   0.73174936  0.7110267 ]
 [-0.50340486 -0.19393474 -0.7359175 ]
 [-0.26575822  0.56630546  0.1893782 ]
 [-0.28152537 -0.46040553  0.08337915]
 [ 0.17656654 -0.8528255  -0.6552073 ]]


In [5]:
print(model.get_weights()[1].shape)
print(model.get_weights()[1])

(3, 3)
[[-0.47803962  0.87789464 -0.02790954]
 [ 0.10441481  0.02524942 -0.9942132 ]
 [ 0.87210983  0.47818756  0.10373546]]


In [6]:
print(model.get_weights()[2].shape)
print(model.get_weights()[2])

(3,)
[0. 0. 0.]


In [7]:
print(model.get_weights()[3].shape)
print(model.get_weights()[3])

(3, 1)
[[-0.5210261]
 [ 1.0315565]
 [ 0.5991092]]


In [8]:
print(model.get_weights()[4].shape)
print(model.get_weights()[4])

(1,)
[0.]


In [14]:
import torch
import torch.nn as nn

class SimpleRNNModel(nn.Module):
    def __init__(self):
        super(SimpleRNNModel, self).__init__()
        self.rnn = nn.RNN(input_size=5, hidden_size=3, batch_first=True)
        self.fc = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out, _ = self.rnn(x)
        out = out[:, -1, :]  # Taking the last output
        out = self.fc(out)
        out = self.sigmoid(out)
        return out

# Instantiate the model
model = SimpleRNNModel()

# Print the model summary
print(model)

# Initialize a sample input
x = torch.randn(1, 4, 5)  # Batch size 1, sequence length 4, input size 5

# Forward pass to initialize weights
model(x)

# Print the shapes of the weights
for name, param in model.named_parameters():
    print(name, param.shape)

SimpleRNNModel(
  (rnn): RNN(5, 3, batch_first=True)
  (fc): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)
rnn.weight_ih_l0 torch.Size([3, 5])
rnn.weight_hh_l0 torch.Size([3, 3])
rnn.bias_ih_l0 torch.Size([3])
rnn.bias_hh_l0 torch.Size([3])
fc.weight torch.Size([1, 3])
fc.bias torch.Size([1])
